sudo: required
services:
 - docker

before_install:
 - docker build -t ksreddy4599/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true ksreddy4599/docker-react npm run test --watchAll=false --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-west-2"
 app: "react-docker"
 env: "ReactDocker-env"
 bucket_name: "elasticbeanstalk-us-west-2-995025397421"
 bucket_path: "react-docker"
 on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
 secure: "$AWS_SECRET_KEY"
 
